### ISSUE TITLE
List technologies used on each project

### ISSUE THREAD

**Issue by BrightnBubbly** [CodeForBoulder/CfB-Website-New#10]
- [ ] On project page

**Comment by alexfinnarn** [comment]
Github apparently uses the Linguist library to decipher what languages are used on a project. 

[https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/](https://help.github.com/articles/my-repository-is-marked-as-the-wrong-language/)

I think pulling this data from Github would be a sufficient starting point. Based on the percentage breakdown of that library, I would hope you could pull that from the API. 

[https://github.com/github/linguist](https://github.com/github/linguist)
