### ISSUE TITLE
existing visitors should be able to easily be updated with the progress of each project

### ISSUE THREAD

**Issue by ashumz** [CodeForBoulder/CfB-Website-New#3]
maybe with a slideshow?

**Comment by natronics** [comment]
How do projects update progress already? Just at stand up? Do commit messages and changes in issue status (e.g., open-->close) count as progress, or is that too granular?

**Comment by alexfinnarn** [comment]
several issues with projects and updates already. I'm going to take a spin with getting as much out of the Github API as possible. I think a template for README.md files would be easier for project maintainers than them updating this new website...even commit messages would work IMHO.
